# Generated by Django 4.1.7 on 2023-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='search_variants',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
